config/routes.rb
Rails.application.routes.draw do
  root 'index#home'
  devise_for :users
  resources :users, except: %i[destroy create] do
    resources :conversations, only: %i[index create] do
      resources :messages, only: [:create]
      member do
        post :close
      end
    end
    resources :posts do
      member do
        post :likes
        post :unlikes
      end
      resources :comments, only: %i[create destroy] do
        member do
          post :likes
          post :unlikes
        end
      end
    end
    member do
      post :follow
      post :unfollow
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  acts_as_likeable
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, lambda { |sender_id, recipient_id|
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  }

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  acts_as_likeable
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable


  has_one :profile, dependent: :destroy
  delegate :first_name, :last_name, :avatar, :interests, :bd, :telephone, :about, to: :profile, prefix: true
  has_many :posts, dependent: :destroy
  has_many :posted_posts, dependent: :destroy, class_name: 'Post', foreign_key: 'author_id'
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :comments

  accepts_nested_attributes_for :profile, update_only: true
  acts_as_follower
  acts_as_followable
  acts_as_liker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, { keys: [:email, :password, :password_confirmation, { profile_attributes: %i[first_name last_name] }] })
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[show edit update destroy likes unlikes]

  def index
    @comments = @post.comments.order(:created_at).page(params[:page]).per(3)
  end

  def show; end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @comment.save!
        format.html { redirect_to :back }
        format.json
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def likes
    current_user.like!(@comment)
    render :like_button_comments
  end

  def unlikes
    current_user.unlike!(@comment)
    render :like_button_comments
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    session[:conversations] ||= []
    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end

  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])
    add_to_conversations unless conversated?
    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])
    session[:conversations].delete(@conversation.id)
    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    return unless current_user
    redirect_to current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
    @message = @conversation.messages.create(message_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: %i[show edit likes unlikes]
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(3)
  end

  def new; end

  def edit; end

  def create
    @post = current_user.posted_posts.create(post_params.merge(user_id: @user.id))
    respond_to do |format|
      if @post.save!
        format.html { redirect_to user_path(@user.id), notice: 'Post was successfully created.' }
        format.js
      end
    end
  end

  def update; end

  def show; end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user.id), notice: 'Post was successfully destroyed.' }
    end
  end

  def likes
    current_user.like!(@post)
    render :like_button
  end

  def unlikes
    current_user.unlike!(@post)
    render :like_button
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:id, :user_id, :author_id, :text, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update follow unfollow load_posts]
  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def new
    @user = User.new
  end

  def update
    respond_to do |format|
      if @user.update(users_params)
        format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def follow
    current_user.follow!(@user) # => This assumes you have a variable current_user who is authenticated
    render :follow_button
  end

  def unfollow
    current_user.unfollow!(@user)
    render :follow_button
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:id, :email, profile_attributes: %i[id first_name last_name avatar bd about interests telephone])
  end
end

app/views/comments/_form.html.haml
= form_for comment do |f|
  - if comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/comments/_index.html.haml
- comments.last(3).each do |comment|
  = render 'posts/comments', comment: comment

app/views/comments/_like_button_comments.html.haml
- if current_user.likes?(comment)
  = link_to unlikes_user_post_comment_path(user, post, comment), method: :post, remote: true do
    %i.fa.fa-heart
- else
  = link_to likes_user_post_comment_path(user, post, comment), method: :post, remote: true do
    %i.fa.fa-heart-o
= comment.likers(User).count

app/views/comments/create.js.haml
$("#post-comments-#{@post.id}").append("#{escape_javascript render('posts/comments', comment: @comment)}");

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/index.js.haml
$("#post-comments-#{@post.id} .load-more").attr('href', "#{user_post_comments_path(@post, page: params[:page].to_i + 1)}");
$("#post-comments-#{@post.id} .comments_block").prepend("#{escape_javascript render('comments/index', comments: @comments )}");

app/views/comments/like_button_comments.js.haml
$(".like_button_comments.post-like-#{@comment.id}").html("#{escape_javascript render(partial: 'comments/like_button_comments', locals: { user: current_user, post: @post, comment: @comment }) }")

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/conversations/_conversation.html.haml
%li
  .panel.panel-default{'data-conversation-id': "#{conversation.id}"}
    .panel-heading
      = link_to "#{conversation.opposed_user(user).profile.first_name} #{conversation.opposed_user(user).profile.last_name}", user_conversations_path(user, conversation), class: 'toggle-window'
      = link_to 'x', close_user_conversation_path(user, conversation), class: 'btn btn-default btn-xs pull-right', remote: true, method: :post
    .panel-body{style: 'display: none'}
      .messages-list
        %ul
          = render 'conversations/conversation_content', messages: conversation.messages, user: user
      = form_for [user,   conversation, conversation.messages.new], remote: true do |f|
        = f.hidden_field :user_id, value: user.id
        = f.text_area :body, class: 'form-control'
        = f.submit 'Send', class: 'btn btn-success'

app/views/conversations/_conversation_content.html.haml
- messages.each do |message|
  = render message, user: user

app/views/conversations/close.js.haml
$('#conversations-list').find("[data-conversation-id='" + "@conversation.id" + "']").parent().remove();

app/views/conversations/create.js.haml
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "#{@conversation.id}" + "']");

if (conversation.length !== 1) {
conversations.append("#{j(render 'conversations/conversation', conversation: @conversation, user: current_user)}");
conversation = conversations.find("[data-conversation-id='" + "#{@conversation.id}" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/conversations/index.html.haml
.row
  .col-md-9
    %ul#conversations-list
      - @conversations.each do |conversation|
        = render 'conversations/conversation', conversation: conversation, user: current_user
  .col-md-3
    .panel.panel-primary
      .panel-heading
        %h3.panel-title Users
      .panel-body
        %ul
          - @users.each do |user|
            %li= link_to "#{user.profile_first_name} #{user.profile_last_name}" , user_conversations_path(user_id: user), remote: true, method: :post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Social
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %a= link_to 'Social', users_path, class: 'navbar-brand'
        %ul.nav.navbar-nav
          %li
            - if user_signed_in?
              = link_to 'profile', user_path(current_user.id), class: 'nav navbar-nav'
          %li
            - if current_user
              = link_to 'conversaton', user_conversations_path(current_user), class: 'nav navbar-nav'
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              - if user_signed_in?
                = link_to 'Выйти', destroy_user_session_path, method: :delete
                %span.glyphicon.glyphicon-log-in
          - else
            %li
              %a{:href => "#"}
                %span.glyphicon.glyphicon-user
                Sign Up
            %li
              - if user_signed_in?
                = link_to 'Выйти', destroy_user_session_path, method: :delete
                %span.glyphicon.glyphicon-log-in
                Login

    = yield

app/views/messages/_message.html.haml
%li
  .row
    %div{class: "#{user.id == message.user_id ? 'message-sent' : 'message-received'}"}
      = message.body

app/views/messages/create.js.haml
var conversation = $('#conversations-list').find("[data-conversation-id='" + "#{@conversation.id}" + "']");
conversation.find('.messages-list').find('ul').append("#{j(render 'messages/message', message: @message, user: current_user)}");
conversation.find('textarea').val('');

app/views/posts/_comments.html.haml
.row.news-coment
  .col-sm-2
    %img= image_tag(comment.user.profile.avatar.url, class: 'image-post')
  .col-sm-5
    .panel.panel-default
      .panel-heading
        %strong= link_to("#{comment.user.profile.first_name} #{comment.user.profile.last_name}", user_path(comment.user))
        %span.text-muted #{comment.created_at.strftime('%-d %B %Y, %H:%M:%S')}
      .panel-body
        = comment.text
  .like_button_comments{class: "post-like-#{comment.id}"}
    - if current_user.likes?(comment)
      = link_to unlikes_user_post_comment_path(comment.post.user, comment.post, comment), method: :post, remote: true do
        %i.fa.fa-heart
    - else
      = link_to likes_user_post_comment_path(comment.post.user, comment.post, comment), method: :post, remote: true do
        %i.fa.fa-heart-o
    = comment.likers(User).count

app/views/posts/_index.html.haml
- posts.last(3).each do |post|
  = render 'users/all_posts', post: post

app/views/posts/_like_button.html.haml
- if current_user.likes?(post)
  = link_to unlikes_user_post_path(user, post), method: :post, remote: true, class: 'btn btn-warning btn-sm  pull-left' do
    %i.fa.fa-thumbs-up
- else
  = link_to likes_user_post_path(user, post), method: :post,  remote: true, class: 'btn btn-warning btn-sm btn-hover pull-left' do
    %i.fa.fa-thumbs-up
= post.likers(User).count

app/views/posts/comment_button.js.haml
$(".comment_button.com-but-#{@post.id}").html("#{escape_javascript render(partial: 'posts/comment_block', locals: { post: @post, user: @user }) }")

app/views/posts/create.js.haml
$("#post-new-#{@user.id}").append("#{escape_javascript render('users/all_posts', post: @post, user: @user)}");

app/views/posts/index.html.haml
- @posts.each do |post|
  %tr
    %td= image_tag post.image.thumb
    %td= post.description

app/views/posts/index.js.haml
$('.load-post').attr('href', "#{user_posts_path(@user, page: params[:page].to_i + 1)}");
$('.posts_block').append("#{escape_javascript render('posts/index', posts: @posts )}");

app/views/posts/like_button.js.haml
$(".like_button.post-like-#{@post.id}").html("#{escape_javascript render(partial: 'posts/like_button', locals: { post: @post, user: @user }) }")

app/views/posts/new.html.haml
%body.bg
  .container
    .row
      .main-login.main-center
        = form_for @post, html: { multipart: true } do |f|
          .field.text-center
            = f.label :text
            = f.text_area :text
          .field.text-center
            = f.label :image
            = f.file_field :image
          .actions
            = f.submit 'Save'

app/views/posts/show.html.haml
.container
  = link_to("Back to #{@user.profile_first_name} #{@user.profile_last_name}", user_path(@user), class: 'btn btn-primary btn-sm btn-hover pull-left fa fa-chevron-left')
  .panel.panel-default
    .panel-heading
      = link_to("#{@post.author.profile.first_name} #{@post.author.profile.last_name}", user_path(@post.author))
      .panel-image
        = image_tag("#{@post.image.url}", class: 'panel-image-preview')
        -#%img.panel-image-preview{src: "#{t.image.url}"}
        %p= @post.text
      .panel-footer.clearfix
        .like_button{class: "post-like-#{@post.id}"}
          = render 'posts/like_button', post: @post, user: @user
        -#= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-danger btn-hover pull-left'

      .comments{id: "post-comments-#{@post.id}"}
        = link_to 'Load more', user_post_comments_path(@user, @post, page: 2), remote: true, class: 'load-more'
        .comments_block
          - @post.comments.order(created_at: :asc).last(3).each do |comment|
            = render 'posts/comments', comment: comment
      .news
        %h5 Add a comment:
        = form_for [current_user, @post, @post.comments.build], remote: true do |f|
          %p
            = f.text_area :text
          %p
            = f.submit

app/views/users/_all_posts.html.haml
.panel.panel-default
  .panel-heading{href: user_posts_path(user)}
    = link_to("#{post.author.profile.first_name} #{post.author.profile.last_name}", user_path(post.author))
    .panel-image
      - if post.image != 0
        = link_to(image_tag("#{post.image.url}", class: 'panel-image-preview'), user_post_path(user, post))
      %p= post.text
    .panel-footer.clearfix
      -#%a.btn.comsys.btn-success.btn-sm.btn-hover.pull-left
      -#  Cmt
      -#  %span.fa.fa-comment
      .like_button{class: "post-like-#{post.id}"}
        = render 'posts/like_button', post: post, user: user
    -#- if post.comments.count != 0
    .comments{id: "post-comments-#{post.id}"}
      = link_to 'Load more', user_post_comments_path(user, post, page: 2), remote: true, class: 'load-more'
      .comments_block
        - post.comments.order(created_at: :asc).last(3).each do |comment|
          = render 'posts/comments', comment: comment
    .news.comments{id: "post-comments-#{post.id}"}
      %h5 Add a comment:
      = form_for [current_user, post, post.comments.build], remote: true do |f|
        %p
          = f.text_area :text
        %p
          = f.submit

app/views/users/_follow_button.html.haml
- if current_user.follows?(user)
  = link_to('Unfollow', unfollow_user_path(user), method: :post, remote: true, class: 'btn-primary btn-sm pull-left', style: 'font-weight: bold')
- else
  = link_to('Follow', follow_user_path(user), method: :post, remote: true, class: 'btn-primary btn-sm btn-hover pull-left', style: 'font-weight: bold')
  -#
  -#%a.btn.btn-primary.btn-sm.btn-hover.pull-left{:href => "#download"}
  -#  Save 
  -#  %span.fa.fa-bookmark

app/views/users/_posts.html.haml
.posts_block{id: "post-load-#{user.id}"}
  - user.posts.order(created_at: :desc).first(3).each do |post|
    = render 'users/all_posts', user: user, post: post
.posts_load{id: "post-load-#{user.id}"}
  = link_to 'load more', user_posts_path(user, page: 2), remote: true, class: 'load-post'

app/views/users/edit.html.haml
%body
  .container
    .row
      .col-md-10
        .main-login.main-center
          = form_for @user, html: { multipart: true } do |f|

            .field.form-group
              = f.label :email, class: 'col-md-4 control-label'
            .input-group
              .input-group-addon
                %i.glyphicon.glyphicon-envelope
              = f.text_field :email, class: 'form-control input-md'

            = f.fields_for :profile do |f2|
              .field.form-group
                = f2.label :first_name, class: 'col-md-4 control-label'
              .input-group
                .input-group-addon
                  %i.glyphicon.glyphicon-user
                = f2.text_field :first_name, class: 'form-control input-md'

              .field.form-group
                = f2.label :last_name, class: 'col-md-4 control-label'
              .input-group
                .input-group-addon
                  %i.glyphicon.glyphicon-user
                = f2.text_field :last_name, class: 'form-control input-md'

              .field.form-group
                = f2.label :bd, class: 'col-md-4 control-label'
              .input-group.date
                .input-group-addon
                  %i.glyphicon.glyphicon-calendar
                = f2.date_field :bd, class: 'form-control input-md'

              .field.form-group
                = f2.label :interests, class: 'col-md-4 control-label'
              .input-group
                .input-group-addon
                  %i.glyphicon.glyphicon-heart-empty
                = f2.text_field :interests, class: 'form-control input-md'

              .field.form-group
                = f2.label :telephone, class: 'col-md-4 control-label'
              .input-group
                .input-group-addon
                  %i.glyphicon.glyphicon-phone
                = f2.phone_field :telephone, class: 'form-control input-md'

              .field.form-group
                = f2.label :about, class: 'col-md-4 control-label'
              .input-group
                .input-group-addon
                  %i.glyphicon.glyphicon-pencil
                = f2.text_area :about, class: 'form-control input-md'

              .field.form-group.text-center
                = f2.label :avatar
                = f2.file_field :avatar, class: 'edit-img'

              .actions.text-center
                = f2.submit 'Save'

app/views/users/follow_button.js.haml
$(".follow-unfollow").html("#{escape_javascript render(partial: 'users/follow_button', locals: { user: @user }) }")

app/views/users/index.html.haml
%h2 welcome

all users
- @users.each do |user|
  %br
  = link_to("#{user.profile_first_name} #{user.profile_last_name}", user_path(user))

app/views/users/show.html.haml
.container
  .row
    .col-sm-3
      .row
        .col-lg-12
          .col-xs-12
            = image_tag("#{@user.profile_avatar.url}", class: 'block-img')
            -#= @user.followers(User).where(@user.follows(User)).count
      .row.panel_friends
        .col-xs-12.panel.panel-default
          .row.panel-heading.text-center
            - if @user.followers(User).count == 0
              %h2 Not friends
            - else
              .text-center Friends
              - @user.followees(User).first(6).each do |user|
                - if user.follows?(@user)
                  .col-xs-4.block_friends
                    = link_to(image_tag("#{user.profile_avatar.url}", class: 'show-img'), user_path(user))
                    %br
                    = link_to("#{user.profile_first_name}", user_path(user))
    .col-xs-12.col-sm-8
      %ul.list-group
        %li.list-group-item #{@user.profile_first_name}
        %li.list-group-item #{@user.profile_last_name}
        %li.list-group-item
          %i.glyphicon.glyphicon-heart
          #{@user.profile_interests}
        %li.list-group-item
          %i.glyphicon.glyphicon-calendar
          #{@user.profile_bd}
        %li.list-group-item
          %i.fa.fa-phone
          #{@user.profile_telephone}
        %li.list-group-item
          %i.fa.fa-envelope
          #{@user.email}
        - if @user.id == current_user.id
          = link_to 'Edit', edit_user_path, class: 'btn btn-primary btn-sm btn-hover pull-left', style: 'font-weight: bold'
        - if current_user != @user
          .follow-unfollow
            = render 'users/follow_button', user: @user
      %h2 About Me
      .blockquote #{@user.profile_about}

      .row
        .col-xs-12
          %h2 Posts
          .posts{id: "post-new-#{@user.id}"}
            %h2 New post

            = form_for [@user, @user.posted_posts.build], remote: true do |f|
              .field
                = f.text_area :text
              .field
                = f.file_field :image
              .actions
                = f.submit 'Save'
      = render 'posts', user: @user